/**
 * Route constants for Router.
 */
/**
 * Route of the login page.
 */
export const LOGIN_ROUTE: string = 'pages/Login';

/**
 * Route of the main index page.
 */
export const INDEX_ROUTE: string = 'pages/Index';

/**
 * Route of page for the ResponsiveLayout.
 */
export const RESPONSIVE_ROUTE: string = 'pages/ResponsiveIndex';

/**
 * Route of page for the AdaptiveLayout.
 */
export const ADAPTIVE_ROUTE: string = 'pages/AdaptiveIndex';

/**
 * Route of page for the SystemCapabilities.
 */
export const SYSTEM_CAPABILITIES_ROUTE: string = 'pages/SystemCapabilitiesIndex';